// The AI-Powered Superintendent — 30 workflows
// Size bands: xs(<500), sm(<1000), md(<3000), lg(<8000), xl(15000+)
// Locale: rural, suburban, urban (all three = universal)
// Domains: hr, curriculum, pupil, board, strategy, labor, crisis, ops
// Featured: 4 (board memo, portrait-to-budget, CBA cost-out, crisis first 90)

const WORKFLOWS = [
  // ───────── BOARD RELATIONS & GOVERNANCE ─────────
  {
    id: 1,
    featured: true,
    tool: "claude",
    toolLabel: "Claude",
    domain: "board",
    domainLabel: "Board & Governance",
    sizes: ["xs","sm","md","lg","xl"],
    locales: ["rural","suburban","urban"],
    title: "Executive Session Memo & Decision Log",
    description: "Turn messy pre-meeting notes into a disciplined executive-session brief with options, recommendations, and a clean decision record.",
    why: "Executive session is where boards get into trouble — wandering conversation, no record, unclear decisions. A disciplined brief protects the board, the district, and the superintendent. It also makes the next morning's follow-up unambiguous.",
    setup: "Paste your raw notes, the legal basis for going into executive session (NY OML §105), the people in the room, and the decision that needs to happen.",
    prompt: "You are a board governance attorney helping me prepare an executive session memo. Using the notes below, produce: (1) a one-line legal basis citing the correct subsection of NY Open Meetings Law §105; (2) a three-sentence situation summary; (3) three options with pros, cons, legal risk, and fiscal impact for each; (4) my recommended option with the reasoning; (5) the specific motion language if the board chooses to act; (6) a decision-log entry template capturing who was present, the question, the motion, the vote, and any dissent — without disclosing deliberative content. Tone: sober, protective of the district, explicitly not legal advice. RAW NOTES: [paste]"
  },
  {
    id: 2,
    tool: "notebooklm",
    toolLabel: "NotebookLM",
    domain: "board",
    domainLabel: "Board & Governance",
    sizes: ["xs","sm","md","lg","xl"],
    locales: ["rural","suburban","urban"],
    title: "Board Policy Reconciler",
    description: "Upload board policy, the CBA, the student handbook, and the faculty handbook. Surface conflicts before parents or unions do.",
    why: "Most districts have four authoritative documents that contradict each other in at least a dozen places. The contradictions surface the worst way — in a grievance or a board complaint. Find them first.",
    setup: "Create a NotebookLM with all four documents loaded. Run this query, then repeat for each major policy area (discipline, evaluation, leave, technology).",
    prompt: "You are a policy reconciler. Using only the documents loaded in this notebook, identify every instance where the board policy, the collective bargaining agreement, the student handbook, and the faculty handbook disagree, contradict, or create ambiguity. For each conflict, produce: (1) the topic in plain English; (2) the exact passage from each document with citations; (3) which document controls legally, and why; (4) which audience is most likely to discover the conflict and file a complaint; (5) a recommended amendment that resolves the conflict. Start with conflicts that touch student discipline, staff evaluation, and leave — those are the highest-risk areas."
  },
  {
    id: 3,
    tool: "claude",
    toolLabel: "Claude",
    domain: "board",
    domainLabel: "Board & Governance",
    sizes: ["xs","sm","md","lg","xl"],
    locales: ["rural","suburban","urban"],
    title: "Board Self-Evaluation Synthesis",
    description: "Turn anonymous board self-evaluation responses into a growth plan the board will actually adopt.",
    why: "Most board self-evaluations produce a PDF that goes in a drawer. The value is in the synthesis — the themes the board won't say out loud but will recognize when they see them on paper.",
    setup: "Paste the anonymized responses from each trustee. Tell Claude how many trustees responded and the dimensions on the rubric.",
    prompt: "You are an experienced board coach (NYSSBA-style). Below are anonymous trustee self-evaluation responses to a [N]-dimension rubric. [N] trustees responded. Produce: (1) the three patterns of strength the full board agrees on, with representative verbatim quotes; (2) the three patterns where the board is divided — describe the split without attributing to any trustee; (3) the one uncomfortable theme the data suggests but trustees mostly talked around; (4) a draft six-month growth plan with three priorities, each with a specific practice to adopt, a measure of progress, and who leads. Keep the tone honest and developmental — boards can tell when a report is sanitized. RESPONSES: [paste]"
  },
  {
    id: 4,
    tool: "chatgpt",
    toolLabel: "ChatGPT",
    domain: "board",
    domainLabel: "Board & Governance",
    sizes: ["md","lg","xl"],
    locales: ["suburban","urban"],
    title: "Board Packet in 90 Minutes",
    description: "Convert a stack of cabinet memos, HR lists, and finance updates into a board-ready packet with consistent voice and a crisp superintendent's report.",
    why: "The packet is the single most read document the superintendent produces. Inconsistent voice, buried asks, and unexplained jargon erode board trust meeting after meeting.",
    setup: "Paste all source materials for the upcoming meeting. Indicate which items are information, action, or consent.",
    prompt: "You are my chief of staff. Below are the raw materials for the next board meeting. Produce a complete packet: (1) a superintendent's report (600–800 words) that opens with one student story, names the strategic priority each major item advances, and ends with an explicit ask or information note; (2) a one-page cover memo for each action item with background, options considered, recommendation, fiscal impact, and the specific motion language; (3) a consent agenda summary; (4) a public-friendly version of the financial update (no jargon, three numbers that matter); (5) a list of every acronym in the packet with plain-English definitions for trustees still learning. MATERIALS: [paste]"
  },

  // ───────── STRATEGIC PLANNING & PORTRAIT OF A GRADUATE ─────────
  {
    id: 5,
    featured: true,
    tool: "claude",
    toolLabel: "Claude",
    domain: "strategy",
    domainLabel: "Strategic Planning",
    sizes: ["xs","sm","md","lg","xl"],
    locales: ["rural","suburban","urban"],
    title: "Portrait of a Graduate → Budget Alignment",
    description: "Walk every line of the proposed budget against the Portrait competencies. Surface what you're funding that doesn't advance the Portrait — and what the Portrait names that the budget ignores.",
    why: "Portraits become wallpaper when they don't touch the budget. This is the single exercise that makes the Portrait real to the board and to taxpayers.",
    setup: "Paste the Portrait competencies and the proposed budget broken down by function/program. Include enrollment and per-pupil spending for context.",
    prompt: "You are a strategic planning consultant. I have pasted our district's Portrait of a Graduate competencies and our proposed budget by function/program. Produce: (1) a crosswalk table showing which budget lines most directly advance each Portrait competency and by how much ($ and % of budget); (2) the three largest budget items that do not clearly advance any Portrait competency — name them, say why, and name what they do advance (compliance, legacy, political necessity, etc.); (3) the two Portrait competencies that are underfunded relative to their prominence in the Portrait — what would meaningful investment look like; (4) three budget moves I could propose to the board that strengthen Portrait alignment without increasing the tax levy; (5) one graphic description I could hand to a designer that shows the alignment at a board meeting in under 30 seconds."
  },
  {
    id: 6,
    tool: "claude",
    toolLabel: "Claude",
    domain: "strategy",
    domainLabel: "Strategic Planning",
    sizes: ["xs","sm","md","lg","xl"],
    locales: ["rural","suburban","urban"],
    title: "Multi-Year Strategic Plan Scaffold",
    description: "Synthesize board priorities, community input, and state accountability indicators into a defensible three-to-five-year plan.",
    why: "Most strategic plans collapse under their own weight — too many priorities, no theory of action, no way to tell if it's working. A tight scaffold with fewer-but-real priorities is the only kind that survives a superintendent transition.",
    setup: "Paste the board's stated priorities, any community survey themes, the district's current accountability data, and demographic trends.",
    prompt: "Act as a strategic planning facilitator with deep experience in NY public districts. Using the materials below, draft a three-year strategic plan scaffold. Produce: (1) one true north statement (not a slogan — a decision rule); (2) no more than four priority areas, each with a why-now rationale grounded in the data; (3) for each priority, a theory of action in the form 'If we ___, then ___, because ___'; (4) two to three leading indicators per priority that would show up in 6–12 months; (5) one hard tradeoff the board will need to accept for each priority (what will get less attention); (6) a one-page executive summary written for a taxpayer, not an educator. MATERIALS: [paste]"
  },
  {
    id: 7,
    tool: "voice",
    toolLabel: "Voice Mode",
    domain: "strategy",
    domainLabel: "Strategic Planning",
    sizes: ["xs","sm","md","lg","xl"],
    locales: ["rural","suburban","urban"],
    title: "Community Input Synthesis (Voice)",
    description: "Walk the building or drive between meetings and talk out what you heard at listening sessions. Get back themes, surprises, and the questions you didn't ask.",
    why: "The best strategic planners process community input out loud, in motion, while it's still fresh. Typing it into a spreadsheet two weeks later loses the texture that matters.",
    setup: "Open Voice Mode on the drive home from the last listening session. No notes needed — the mode pulls the memory.",
    prompt: "I just finished a community listening session on our strategic plan. I'm going to describe what I heard out loud. You're going to listen, ask me two or three clarifying questions, and then play back to me: (1) the three themes I said most often; (2) the one constituency whose voice was quieter than it should have been; (3) the one thing I heard that contradicts what I thought the community believed; (4) the question I didn't ask but should have; (5) one follow-up action I can take this week that would show I was listening. Ready when I am."
  },
  {
    id: 8,
    tool: "chatgpt",
    toolLabel: "ChatGPT",
    domain: "strategy",
    domainLabel: "Strategic Planning",
    sizes: ["md","lg","xl"],
    locales: ["suburban","urban"],
    title: "Superintendent KPI Dashboard Design",
    description: "Design a one-page dashboard that tells a board in 60 seconds whether the strategic plan is working.",
    why: "Boards drown in data. What they need is three to five numbers that move when the plan works — and a narrative for each that distinguishes signal from noise.",
    setup: "Paste your strategic priorities, the state accountability indicators you're required to report, and any local measures you care about.",
    prompt: "You are a data visualization designer for public school governance. Using my strategic priorities and available data sources below, design a one-page KPI dashboard. Produce: (1) the three to five headline indicators that would show the plan is working, with the exact measure, the data source, the reporting cadence, and the target; (2) for each indicator, a short narrative explaining what it captures and what it does not; (3) a visual layout described for a designer — no dashboards wider than a single screen, accessible color, no 3D; (4) three indicators to deliberately exclude and why (vanity metrics, lagging-beyond-usefulness, gameable); (5) a board-talking-points script for presenting this at the first meeting. PRIORITIES & DATA: [paste]"
  },

  // ───────── LABOR NEGOTIATIONS & CBA STRATEGY ─────────
  {
    id: 9,
    featured: true,
    tool: "notebooklm",
    toolLabel: "NotebookLM",
    domain: "labor",
    domainLabel: "Labor & Negotiations",
    sizes: ["xs","sm","md","lg","xl"],
    locales: ["rural","suburban","urban"],
    title: "CBA Cost-Out & Comparator Scan",
    description: "Load the current CBA, the proposed language, and two to three comparator-district contracts. Get a multi-year cost model and a comparator analysis in minutes.",
    why: "The single most expensive decision a superintendent makes — and the one most often made with back-of-the-envelope math. Comparator analysis done right gives the board confidence and the union a common language.",
    setup: "NotebookLM with: current CBA, negotiator's proposal, two to three comparator district contracts, current salary schedule, and headcount by step.",
    prompt: "You are a labor relations analyst. Using only the documents in this notebook: (1) model the three-year cost of the proposed contract against the current contract, broken out by salary, health insurance, longevity, stipends, and retirement — cite the specific article and page for each driver; (2) compare the proposed economic package to the comparator district contracts loaded here on the same dimensions; (3) identify the three non-economic articles where the proposed language materially shifts management rights (evaluation, transfer, assignment, discipline); (4) flag any article where the proposed language conflicts with state law, commissioner's regulations, or current board policy; (5) draft three counter-proposals — one conservative, one moderate, one aggressive — with rationale and likely union response. Cite article, section, and page for every claim. If the documents are silent, say so."
  },
  {
    id: 10,
    tool: "claude",
    toolLabel: "Claude",
    domain: "labor",
    domainLabel: "Labor & Negotiations",
    sizes: ["xs","sm","md","lg","xl"],
    locales: ["rural","suburban","urban"],
    title: "Bargaining Team Briefing Deck",
    description: "Turn a messy pile of cost-outs, comparator data, and board priorities into a bargaining team briefing that actually prepares the team.",
    why: "Bargaining teams lose at the table because they were never aligned before they sat down. A shared briefing that names the red lines, the trades, and the story the board will tell taxpayers is the difference between a good settlement and a costly one.",
    setup: "Paste your cost-out summary, comparator findings, board priorities (public and executive-session), and the union's known asks.",
    prompt: "You are the chief negotiator coaching the district's bargaining team. Produce a team briefing with: (1) the board's top three priorities translated into bargaining positions, with the red line for each; (2) a trade map — if we give X, we aim to get Y — with at least five pairings; (3) a comparator-district narrative the board can defend publicly (we are fair, we are competitive, we are sustainable); (4) the three hardest questions the union will ask and the team's pre-agreed answers; (5) the signal-and-noise guide — what to say yes to quickly, what to slow-walk, what to take caucus on; (6) a one-page cheat sheet the team can keep at the table. MATERIALS: [paste]"
  },
  {
    id: 11,
    tool: "notebooklm",
    toolLabel: "NotebookLM",
    domain: "labor",
    domainLabel: "Labor & Negotiations",
    sizes: ["xs","sm","md","lg","xl"],
    locales: ["rural","suburban","urban"],
    title: "Grievance Precedent Scan",
    description: "Load past grievances, arbitrator decisions, and your CBA. Ask whether the current situation has been litigated before.",
    why: "New superintendents reinvent the wheel on every grievance. The institution already knows the answer — the knowledge is in a filing cabinet nobody reads.",
    setup: "NotebookLM with at least five years of grievance files, arbitrator or PERB decisions, and the CBA.",
    prompt: "You are my labor relations historian. A grievance has been filed with the following fact pattern: [paste]. Using only the documents loaded in this notebook: (1) identify the three most similar past grievances and summarize each with outcome and reasoning; (2) identify any arbitrator or PERB decision that squarely governs; (3) tell me which contract articles are in play and whether past practice has modified them; (4) recommend a step-one response strategy with language the principal can use; (5) flag any angle the union will likely raise that the district has lost on before. Cite specific documents and pages."
  },
  {
    id: 12,
    tool: "chatgpt",
    toolLabel: "ChatGPT",
    domain: "labor",
    domainLabel: "Labor & Negotiations",
    sizes: ["md","lg","xl"],
    locales: ["suburban","urban"],
    title: "Sunshine & Transparency Messaging",
    description: "Draft the community-facing narrative during and after negotiations — legal, fair, human, and specific.",
    why: "The loudest voice in a bargaining cycle is often the last one the district hears from. A clear, disciplined public narrative changes that.",
    setup: "Paste the settlement terms or current proposal status, the context (labor climate, comparator settlements), and the audience (taxpayers, staff, parents, media).",
    prompt: "You are a public affairs director for a school district. Draft three pieces of communication about the current round of negotiations: (1) a 400-word letter to the community from the superintendent — honest about tradeoffs, grounded in comparator data, not triumphalist; (2) a staff-facing message that acknowledges the work done at the table without leaking strategy; (3) a media statement of under 120 words for any reporter who asks. Tone: respectful of the union, transparent about tax impact, never adversarial. No euphemism. No jargon. SETTLEMENT/STATUS: [paste]"
  },

  // ───────── CRISIS COMMS & COMMUNITY TRUST ─────────
  {
    id: 13,
    featured: true,
    tool: "claude",
    toolLabel: "Claude",
    domain: "crisis",
    domainLabel: "Crisis Comms",
    sizes: ["xs","sm","md","lg","xl"],
    locales: ["rural","suburban","urban"],
    title: "Crisis Comms — First 90 Minutes",
    description: "A stranger-danger lockdown, a student loss, a social-media wildfire. Get a coordinated comms plan for the window that defines the aftermath.",
    why: "The first 90 minutes of a crisis create the narrative the community will carry for years. Improvised comms in that window produce lasting damage. A pre-thought structure survives the adrenaline.",
    setup: "Describe the incident type, what is currently confirmed, what is not, the population affected, and the legal constraints (FERPA, active investigation, coroner's office).",
    prompt: "You are my crisis communications director. An incident has just occurred. Details: [paste]. Within the next 90 minutes, produce: (1) a 2-sentence first message to staff (what happened, what to do); (2) a 3-sentence message to parents via the district notification system — factual, compassionate, no speculation; (3) a holding statement for media of under 60 words; (4) a talking-points brief for building principals fielding calls; (5) a list of what we are explicitly NOT saying yet and why (investigation integrity, FERPA, family wishes); (6) the follow-up comms cadence for the next 24 hours with specific times and audiences. Tone: calm, concrete, protective of affected families, never defensive."
  },
  {
    id: 14,
    tool: "chatgpt",
    toolLabel: "ChatGPT",
    domain: "crisis",
    domainLabel: "Crisis Comms",
    sizes: ["xs","sm","md","lg","xl"],
    locales: ["rural","suburban","urban"],
    title: "Parent Letter — Student Loss",
    description: "The hardest letter a superintendent ever writes. A frame that honors the family, supports the community, and names where to get help.",
    why: "In the moment, superintendents freeze or over-edit. A structural frame lets the human voice come through without losing the elements the community needs.",
    setup: "Tell the model the age of the student (not the name), what is known that the family has consented to share, and the in-district supports available.",
    prompt: "I am writing a community letter about the loss of a student. What the family has authorized me to share: [paste]. What is known about circumstances: [paste — or 'not disclosed']. Produce a letter with: (1) an opening that names the student and the community's loss without euphemism; (2) what we know the family wants the community to understand; (3) the supports available at school tomorrow — people, places, times, and what to do if a student is struggling; (4) a reminder about safe messaging around young people and loss (no details of means, focus on the person); (5) a close from me, in first person, that sounds like a human being, not an office. Length: 350–450 words. Do not use the words 'processing' or 'our thoughts.'"
  },
  {
    id: 15,
    tool: "voice",
    toolLabel: "Voice Mode",
    domain: "crisis",
    domainLabel: "Crisis Comms",
    sizes: ["xs","sm","md","lg","xl"],
    locales: ["rural","suburban","urban"],
    title: "Press Conference Rehearsal",
    description: "Practice the hardest questions aloud before you take the podium. AI plays a skeptical reporter.",
    why: "Podiums are unforgiving. The soundbite that runs for two weeks is almost always the answer to a question the superintendent didn't rehearse.",
    setup: "Open Voice Mode in the car on the way to the district office. Describe the situation out loud.",
    prompt: "Role-play as a skeptical local TV reporter preparing for a press conference on the following situation: [describe]. Ask me the five hardest questions you would ask in that order. Don't let me off the hook. If I hedge, follow up. If I dodge, name the dodge. After the last question, drop role and tell me: (1) the two answers that were strongest and why; (2) the one moment I gave them a soundbite that will hurt us; (3) one sentence I should rehearse out loud three more times before I walk in."
  },
  {
    id: 16,
    tool: "claude",
    toolLabel: "Claude",
    domain: "crisis",
    domainLabel: "Crisis Comms",
    sizes: ["md","lg","xl"],
    locales: ["suburban","urban"],
    title: "Restorative Follow-Up Plan",
    description: "The crisis is over. Now the harder work begins — repairing trust with students, staff, and families without performing repair.",
    why: "Most districts treat the end of the emergency as the end of the work. The families who lost trust during the 90 minutes remember for years. Restorative follow-up is what keeps people in the district.",
    setup: "Describe the incident, the populations affected, and any feedback received since the initial response.",
    prompt: "You are a restorative practices consultant. An incident is resolved on the operational side, but trust is damaged. Incident and aftermath: [paste]. Produce a 30/60/90-day restorative plan: (1) the three populations most harmed (name them specifically — not 'the community'); (2) for each, one structured listening opportunity in the next 30 days (format, facilitator, ground rules); (3) one concrete change by day 60 that visibly responds to what was heard; (4) one narrative by day 90 that tells the community what changed because of what they said; (5) the trap to avoid — the restorative move that would feel like performance and make it worse. No buzzwords."
  },

  // ───────── CURRICULUM & INSTRUCTION ─────────
  {
    id: 17,
    tool: "claude",
    toolLabel: "Claude",
    domain: "curriculum",
    domainLabel: "Curriculum & Instruction",
    sizes: ["xs","sm","md","lg","xl"],
    locales: ["rural","suburban","urban"],
    title: "District Curriculum Audit",
    description: "Feed every scope-and-sequence, pacing guide, and unit assessment into a single review. Find the gaps, the duplications, and the vertical alignment breaks.",
    why: "Most districts cannot describe their K–12 curriculum because nobody has read all of it in one sitting. The seams between grade bands are where students get lost.",
    setup: "Upload scope-and-sequence documents K–12 in a specific content area. Tell Claude which standards framework applies.",
    prompt: "You are a curriculum coordinator with deep K–12 content expertise in [SUBJECT]. Audit the uploaded documents. Produce: (1) a K–12 standards coverage map — which standards are addressed, where, and with how much instructional time; (2) the three standards that are taught in multiple grades with overlapping rigor (redundancy) and where to consolidate; (3) the three standards that are named in the documents but never assessed; (4) the two grade-band transitions where vertical alignment is weakest (e.g., 5→6, 8→9); (5) one teacher-facing summary per grade that names what they inherit, what they're responsible for, and what they hand off."
  },
  {
    id: 18,
    tool: "claude",
    toolLabel: "Claude",
    domain: "curriculum",
    domainLabel: "Curriculum & Instruction",
    sizes: ["xs","sm","md","lg","xl"],
    locales: ["rural","suburban","urban"],
    title: "Assessment Audit & Time Inventory",
    description: "Find out exactly how many hours your students spend testing — and which assessments are generating the insight worth that time.",
    why: "Districts accumulate assessments like layers of sediment. Nobody decides to remove one. The result is a test calendar that crowds out teaching and nobody can defend line by line.",
    setup: "Upload the district assessment calendar, any benchmark results you're willing to share, and the purpose statement (if any) for each assessment.",
    prompt: "You are an assessment systems expert. Audit the district's assessment calendar I've uploaded. Produce: (1) total student testing minutes by grade, including make-ups; (2) for each assessment, the decision it informs — instruction, placement, accountability, school-level, or none; (3) the three assessments with the weakest decision-linkage; (4) the two assessments that duplicate information from another instrument; (5) a revised calendar that reduces testing time by at least 25% while preserving the decisions that matter; (6) a one-paragraph rationale I can share with teachers who will ask 'why are we still doing this one?'"
  },
  {
    id: 19,
    tool: "claude",
    toolLabel: "Claude",
    domain: "curriculum",
    domainLabel: "Curriculum & Instruction",
    sizes: ["xs","sm","md","lg","xl"],
    locales: ["rural","suburban","urban"],
    title: "Academic Vocabulary From State Assessments",
    description: "Upload three to five years of Regents or state tests. Get the high-frequency academic vocabulary that actually matters — ranked, defined, and teachable.",
    why: "The same 40 Tier-2 words appear on Regents exams year after year. Districts that teach them explicitly — not just in ELA, but everywhere — move the needle more than any single curriculum purchase.",
    setup: "Upload the released state assessments for the content area and grade band you want to analyze.",
    prompt: "Analyze the state assessments I have uploaded. I am a superintendent and I want to give my K–12 teachers a vocabulary list that will move the needle on student performance. Produce: (1) the top 40 academic vocabulary terms ranked by frequency across years; (2) for each term: how often it appears, the kinds of items it shows up in, and a student-friendly definition; (3) cluster the list into Tier 2 general academic vs. Tier 3 discipline-specific, and recommend which grade introduces each cluster; (4) for the 10 highest-frequency terms, draft a grade-level example sentence in the context students will see on the test; (5) flag any terms easily confused with similar-looking words."
  },
  {
    id: 20,
    tool: "claude",
    toolLabel: "Claude",
    domain: "curriculum",
    domainLabel: "Curriculum & Instruction",
    sizes: ["xs","sm","md"],
    locales: ["rural","suburban"],
    title: "Shared Curriculum Map — Small District",
    description: "For districts where the superintendent IS the curriculum director. A full-year map in a content area, co-designed in 60 minutes.",
    why: "In districts under 3,000 students, the superintendent often wears the curriculum hat. A disciplined scaffold means the whole job doesn't take a semester of nights and weekends.",
    setup: "Upload standards, your staffing reality (how many sections, how many teachers), and any existing materials.",
    prompt: "Act as an expert curriculum designer for a small district. I am the superintendent AND the curriculum coordinator. Using the standards and context I have uploaded, draft a complete year-long map for [SUBJECT, GRADE]. Produce: (1) pacing overview with unit names, calendar weeks, and standards covered; (2) for each unit — enduring understanding, essential questions, anchor texts with alternatives at three reading levels, three formative checks and one summative task, vocabulary list with academic terms that carry weight on state assessments, two authentic performance opportunities beyond the test; (3) a cross-unit literacy arc. After the map, list five decisions you had to make as the designer that you want me to weigh in on before I share this with teachers."
  },

  // ───────── PUPIL PERSONNEL & STUDENT SERVICES ─────────
  {
    id: 21,
    tool: "claude",
    toolLabel: "Claude",
    domain: "pupil",
    domainLabel: "Pupil Personnel",
    sizes: ["xs","sm","md","lg","xl"],
    locales: ["rural","suburban","urban"],
    title: "CSE/504 Pattern Finder",
    description: "Paste de-identified CSE and 504 data. Find the patterns — over-classification, disproportionality, service-delivery gaps — that no one on staff can see from inside the system.",
    why: "The most expensive and legally-sensitive program in the district is the one superintendents have the least direct visibility into. Patterns surface when somebody outside the day-to-day looks at the data.",
    setup: "Paste a de-identified table of classification rates, service minutes, and outcomes by grade, school, and demographic group. Use codes instead of names.",
    prompt: "You are a special education auditor. Using the de-identified data below, identify: (1) any disproportionality by race, gender, or English learner status that exceeds the state's risk-ratio threshold; (2) buildings or grades where classification rates differ significantly from the district mean; (3) service-delivery patterns that suggest capacity issues (minutes not delivered, co-teaching without co-planning, related services clustered in certain rooms); (4) the three highest-leverage interventions the district could take in the next 90 days; (5) the one question the board should be asking me at the next meeting that the data makes unavoidable. DATA: [paste]"
  },
  {
    id: 22,
    tool: "claude",
    toolLabel: "Claude",
    domain: "pupil",
    domainLabel: "Pupil Personnel",
    sizes: ["xs","sm","md","lg","xl"],
    locales: ["rural","suburban","urban"],
    title: "Attendance Intervention Map",
    description: "Move from chronic absenteeism percentages to a tiered, named intervention plan the whole district can execute.",
    why: "Chronic absenteeism is the single strongest leading indicator of everything else. The data is easy to see; the response is where districts get lost.",
    setup: "Paste attendance data by building, grade, and demographic group. Include any existing intervention steps.",
    prompt: "You are a student services director. Using the attendance data below: (1) identify the buildings and grade bands with the highest chronic absenteeism; (2) for each, the three most likely underlying drivers in that context (transportation, mental health, family instability, disengagement); (3) a tiered intervention map — universal (all students), targeted (5–15%), intensive (1–5%) — with who leads each tier and what escalation looks like; (4) a first-contact script for the home-outreach call that is warm, specific, and does not lead with consequences; (5) three leading indicators that would show the interventions are working in 30 days. DATA: [paste]"
  },
  {
    id: 23,
    tool: "claude",
    toolLabel: "Claude",
    domain: "pupil",
    domainLabel: "Pupil Personnel",
    sizes: ["md","lg","xl"],
    locales: ["suburban","urban"],
    title: "Discipline Equity Review",
    description: "Analyze discipline data for disproportionality, escalation patterns, and the friction points where minor infractions become suspensions.",
    why: "Discipline data tells the story of how a district feels to its most vulnerable students. Patterns here predict graduation rates, special education referrals, and juvenile justice contact.",
    setup: "Paste discipline data by building, grade, offense type, and demographic group. De-identify students.",
    prompt: "You are an equity auditor. Using the de-identified discipline data below: (1) compute risk ratios for suspension and referral by race, gender, IEP status, and English learner status; (2) identify the three most common offense categories driving disproportionality and what the research says about their discretionary nature; (3) the three buildings or grades with the widest gaps between demographic groups; (4) the specific moments in the escalation ladder (referral → conference → ISS → OSS) where bias most likely enters and what interrupts it; (5) three changes in discipline policy or practice that would compress the gap without reducing accountability. DATA: [paste]"
  },
  {
    id: 24,
    tool: "notebooklm",
    toolLabel: "NotebookLM",
    domain: "pupil",
    domainLabel: "Pupil Personnel",
    sizes: ["xs","sm","md","lg","xl"],
    locales: ["rural","suburban","urban"],
    title: "McKinney-Vento & Homeless Liaison Agent",
    description: "Turn federal law, state regulation, and district procedure into a conversational expert for the homeless liaison and school-based staff.",
    why: "McKinney-Vento questions come up at 4:47 PM on a Friday. The stakes for the family are immediate and the staff member asking does not have time to read the statute.",
    setup: "Build a NotebookLM with: McKinney-Vento statute, NYSED guidance, your district's transportation and enrollment procedures, and your board policy.",
    prompt: "You are our district's McKinney-Vento advisor. Based only on the documents in this notebook, answer the question below with citations to specific rule, page, or section. Rules: Cite every claim. If the documents are silent, say so. If federal and state requirements differ, surface both. Flag anything that calls for attorney or county contact. Never make the family prove more than the law requires. QUESTION: [e.g., 'A family is staying with a cousin after losing their apartment. The cousin lives in the next district. The child currently attends our high school. What are our obligations?']"
  },

  // ───────── HR & PERSONNEL ─────────
  {
    id: 25,
    tool: "notebooklm",
    toolLabel: "NotebookLM",
    domain: "hr",
    domainLabel: "HR & Personnel",
    sizes: ["xs","sm","md","lg","xl"],
    locales: ["rural","suburban","urban"],
    title: "Civil Service Personnel Agent",
    description: "Turn county civil service rules and your district's non-instructional procedures into an on-call advisor for hiring support staff.",
    why: "Non-instructional hiring is where most compliance exposure lives — and where most superintendents have the least training. A citation-grounded advisor is worth its weight at 5 PM on a Friday.",
    setup: "NotebookLM with the county civil service rules, local job descriptions, your board's hiring procedures, and any past MOAs that govern the roles.",
    prompt: "You are an expert on [COUNTY] civil service rules and our district's non-instructional personnel procedures. Using only the uploaded documents: (1) answer my questions with citations to the specific rule or job description; (2) if I describe a situation, tell me whether a proposed action is compliant, and what the alternative is; (3) if a decision requires a competitive list, tell me which list, how canvassing works, and what our obligations are; (4) never guess — if the documents are silent or unclear, say so and suggest who to contact. My situation: [describe]"
  },
  {
    id: 26,
    tool: "claude",
    toolLabel: "Claude",
    domain: "hr",
    domainLabel: "HR & Personnel",
    sizes: ["md","lg","xl"],
    locales: ["suburban","urban"],
    title: "Cabinet Structure & Span of Control",
    description: "Redesign the central-office org chart around the work that actually matters — not the one inherited from three superintendents ago.",
    why: "Most cabinet charts are artifacts, not designs. They reflect the last reorganization, the last retirement, and the last political accommodation. Redesigning around the work is one of the highest-leverage moves a superintendent makes.",
    setup: "Paste your current org chart with FTEs and salaries, your strategic priorities, and the three things cabinet currently spends the most time on.",
    prompt: "You are an organizational design consultant for public districts. Using the materials below: (1) map the current cabinet structure against the district's stated strategic priorities — where is there misalignment; (2) identify the three roles whose job description has drifted furthest from what the work actually requires; (3) propose a revised cabinet structure with reporting lines, span of control, and the work each role owns — without increasing headcount; (4) name the two hardest political or cultural shifts this structure would require; (5) draft a 90-day implementation sequence that doesn't destabilize the district mid-year. CURRENT STATE: [paste]"
  },
  {
    id: 27,
    tool: "voice",
    toolLabel: "Voice Mode",
    domain: "hr",
    domainLabel: "HR & Personnel",
    sizes: ["xs","sm","md","lg","xl"],
    locales: ["rural","suburban","urban"],
    title: "Superintendent Interview Prep — Both Sides",
    description: "Prep for the final-round interview — as the one being interviewed, or as the board chairing it. Voice Mode role-plays the other side.",
    why: "The single highest-stakes conversation in public education is the superintendent interview. Both sides routinely walk in under-rehearsed.",
    setup: "Voice Mode on a walk. State which role you're playing — candidate or board chair — and the district profile.",
    prompt: "Role-play a final-round superintendent interview. I am the [candidate / board president]. The district is [size, locale, key challenge, current political dynamics]. Run a 45-minute structured interview. For a candidate: ask the five hardest questions a thoughtful board would ask — instructional vision, conflict with a board member, first 90 days, equity, a failure. For a board chair: play a strong candidate who gives sharp, honest answers, and push me on whether I'm asking for what the district actually needs. When we're done, give me feedback on (1) the answer or question that was strongest, (2) the moment I lost the room, (3) one thing to rehearse before the real thing."
  },
  {
    id: 28,
    tool: "claude",
    toolLabel: "Claude",
    domain: "hr",
    domainLabel: "HR & Personnel",
    sizes: ["xs","sm","md"],
    locales: ["rural","suburban"],
    title: "Cabinet of One — Small District Delegation Map",
    description: "In districts under 3,000, the superintendent is frequently HR, curriculum, and transportation. A disciplined delegation map is how the job stays human.",
    why: "Small-district superintendents burn out because nobody ever tells them which parts of the job they are allowed to hand off. A delegation map gives them permission.",
    setup: "List every function you currently touch in a typical week, and rank them by stakes and by energy cost.",
    prompt: "You are a coach for small-district superintendents. I have pasted my weekly function list below. Produce: (1) the three functions only I can do, by law or by leadership necessity; (2) the three functions currently on my plate that should be explicitly delegated to a building principal, business official, or board subcommittee — name the person and the handoff; (3) the three functions that should be partially automated or done once-per-quarter rather than once-per-week; (4) one function I should stop doing entirely and what would happen if I did; (5) a one-page handoff memo template I can use for each delegation. LIST: [paste]"
  },

  // ───────── FINANCE, OPERATIONS & FACILITIES ─────────
  {
    id: 29,
    tool: "chatgpt",
    toolLabel: "ChatGPT",
    domain: "ops",
    domainLabel: "Finance & Operations",
    sizes: ["xs","sm","md","lg","xl"],
    locales: ["rural","suburban","urban"],
    title: "Budget Narrative for Taxpayers",
    description: "Turn a 120-page budget document into a one-page story a taxpayer can read over coffee and understand what their money buys.",
    why: "Budgets pass or fail on whether the community understands them. Jargon-dense documents lose even sympathetic voters. Clarity is the single highest-leverage move.",
    setup: "Paste the proposed budget summary, the tax levy impact, and any major changes from last year.",
    prompt: "You are a public finance writer. Turn the budget materials below into a one-page community narrative. Produce: (1) a lede that names the single most important thing a taxpayer should know; (2) three numbers that matter — tax levy change, per-pupil spending, state aid trend — with plain-English explanations; (3) three things this budget lets the district do that last year's did not; (4) one thing this budget does not fund and why; (5) where a taxpayer goes with questions — an email, a forum, a meeting time. No acronyms without definitions. Reading level: motivated high schooler. MATERIALS: [paste]"
  },
  {
    id: 30,
    tool: "chatgpt",
    toolLabel: "ChatGPT",
    domain: "ops",
    domainLabel: "Finance & Operations",
    sizes: ["md","lg","xl"],
    locales: ["suburban","urban"],
    title: "Capital Project / Bond Messaging Arc",
    description: "Plan a 12-month community engagement and messaging arc for a capital project or bond vote — from first community forum to ballot day.",
    why: "Bonds fail when districts start talking to the community three months before the vote. The districts that pass theirs have been in conversation for a year.",
    setup: "Paste the project scope, the dollar amount, the tax impact, and the known community sentiment.",
    prompt: "You are a bond campaign strategist (ethical, public-interest, not paid political). Design a 12-month community engagement and messaging arc for the capital project below. Produce: (1) four phases with goals, audiences, and channels for each (awareness, information, engagement, activation); (2) the three most likely objections from the community and the evidence-based response to each; (3) an accessibility plan that reaches renters, non-parents, and senior taxpayers, not just parent-council regulars; (4) the three moments between now and vote day where a misstep would sink the project; (5) a one-page steering committee charter with meeting cadence and decision rights. PROJECT: [paste]"
  }
];
